# Generated by Django 4.2.2 on 2023-06-12 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.TextField(blank=True)),
                ('ruta', models.TextField(blank=True)),
                ('HoraInicio', models.DateTimeField(blank=True, null=True)),
                ('HoraFin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('es_Guia', models.BooleanField(blank=True, default=False)),
                ('es_Cliente', models.BooleanField(blank=True, default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='servicio',
            name='userUsuarioCustom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuariopersonalizado'),
        ),
    ]
