# Generated by Django 4.2.2 on 2023-06-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='cantidadpasajeros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='detallesadicionales',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='incluircomida',
            field=models.BooleanField(default=False),
        ),
    ]
