# Generated by Django 4.2.1 on 2023-06-04 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_usuariocliente_alter_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.TextField(blank=True)),
                ('ruta', models.TextField(blank=True)),
                ('HoraInicio', models.DateTimeField(blank=True, null=True)),
                ('HoraFin', models.DateTimeField(blank=True, null=True)),
                ('userCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuariocliente')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('placa', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='servicio',
            name='userGuia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuarioguia'),
        ),
    ]
