# Generated by Django 4.2.2 on 2023-06-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
